apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: dev-cd-deploy-from-master-template
  namespace: gitops-cicd-environment
spec:
  params:
  - description: The specific commit SHA.
    name: gitsha
  - description: The git repository url
    name: gitrepositoryurl
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      creationTimestamp: null
      name: dev-cd-pipeline-run-$(uid)
    spec:
      pipelineRef:
        name: dev-cd-pipeline
      resources:
      - name: source-repo
        resourceSpec:
          params:
          - name: revision
            value: $(params.gitsha)
          - name: url
            value: $(params.gitrepositoryurl)
          type: git
      - name: runtime-image
        resourceSpec:
          params:
          - name: url
            value: image-registry.openshift-image-registry.svc:5000/example/repo:$(params.gitsha)
          type: image
      serviceAccountName: pipeline
    status: {}
status: {}
---
