metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: staging
spec:
  encryptedData:
    webhook-secret-key: AgA9bejuHemTjvS4AHedCTEBY4jNlvTht0gKd1A4njB24VAtC4s1qfGVVg66pzjfUJhq9M3bK07zhYgidgx+6+oo67EZDXXJz7wPZcTnzdepFmsu3tiw1fV7uWswZ9tN5rDumL9sBLTkNHOnxcdCaK9MUTqvNONTAKFpoi/BL1BWZYCBVEsqU8T6OcFkvDrt0HJ+RdZmLvOPRPz+QQZ6S6ymsBUacfE0vQbHwOxLE6mmNrLJclaLI7BTo4hNHq3G8srQcZr7QO7mxnafzKD/7ZHnp22QpJbXsCDNBFc8t0ZolwtKa4wIypWTf/53vjPT25odiqq1uSu50TcPDWkPaSla1MWY63P6vopT6KACj3zX+tc5cRoO/kRUsjcGk8aFTPfN2Jm8LP15gsCvb2EvPyV7GgXaYPybDYqqpa+GJl7hE1zQMOYVei4ZdHQGWcmvy1e54ZElqHVbP07aSiKqxu4sxMN5QtQM0hvmYLgr9pK+HzxHk5K7kWHkQehv+VQR3sR4g/D139DlzFY4OTuvWpr1ile4/Mp8zcFOEtAgj30gkacrTjNkFgOfXVZN03eDmqAumzdf1bxG9B1SvrirQtlMfsodGllHUKxm7eMGPZu/WnickOfPpNNaGv9z/HGv8G0+Q/rhsQ4CeXpbfnTLa06cmV1bYc6RKI2rPXOsQVK9Hwj6jZvYjgknimarUDX1aV9t7Ikb9QsZIBInXv8=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: staging
    type: Opaque
status: {}
---
