metadata:
  creationTimestamp: null
  name: regcred
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgBHD2wkjcW2QEpFclxemt7m1hMSLY0V0I8e07S4MtTH0uTuU/P9wwvvP55+r9UTRCakwb09KauZqu2HcvhPm06YNccPE+/vC3OqIb6zpnwLga7bSJwh7UHSZhLERgIMpPqwouLMWkzNFJ4kNByIyN/eydNCqBlwH8gZ8kG+HqE4RlsvbQACrRuD8Y9J78FqbySB2LMKijapjrSSSHeyPM6hjxoku4o+ALnn86XIcn8aguxirET1gwuQzngjwUFjB5FY4MdBOXag51YPICu0Au12zhTDRauOao3DaAdhvQTVAhRyfz7CYOWKaMQFE0ZTJl96QPGNIC3Yp8bPx/+DhQBKl4ZzhDmnlqKHSK0f5zdA9OpDHnsseYvLp+TRpWaghlvHoR+dB8KwOJQAFOTkoZddRr3/bQ4rKXSg+fHskfgSNlfBOy6e3266ih8MZllrxXraX7GW+pGlP/7dPFtHoYvaZ2BPb+qM5jgiaQb0Abe4tpEiRWgcBlJn4hjyCMWDPODUXPA1q9B7fPzDUP2gcNGvBnpPxLzTM+kHKJn30afNkzrU3DXlmyn+rxpA9f/OLZjTn7pyNRqnSdl9K1HMdsCIp3dl2bhnVMUglknYgO3jH/RmR421LD35HTyyTmkm+HlRCFZfQcgM0oQl1cIwAWDnL2oN1Am8x7nedoD9Xf4mlz9X/fTwPrfZaPCVEq2bAdikmRLQDZQbySr24NmzPHCVQbmIEi3nclivREUfOtvZ9axrddQWEWaJnH0RWdR6kPOJKoedyU31euPIDIDyWM3XKs4FdAGnVR3IEuJuBDNVskafu3/ER31NYpHDK2tvGX4GrvCA6sFp6iz5+jsyZlz0qo7Wcj/12CS69o5unDC2FGRahR1+5VVc2d0hHOF8/cPii6EqguLUlugCqcBY0DZw84Dwur4kzemS/DXO/b1+
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: staging
    type: kubernetes.io/dockerconfigjson
status: {}
---
