metadata:
  creationTimestamp: null
  name: regcred
  namespace: gaganeggday
spec:
  encryptedData:
    .dockerconfigjson: AgAa8wEvlkEU/QLEH2YgNVAThrDNfhhYR/UKOkK5iFkIb76d119+477f1dtZziVuv9LMw3nqTMt4k+LGlhalYqA7M43uqgkZJgfzEyohDQY39NA5rWUAJ+dAZbQ2XK49q6ZjwJ8/Mcs6XzBbQNAdquE4G4EbbA2Cc1nd6dSx0KGk6Blz3E0V5EwJe0ZRtzwmCmznlYN2N5XE0MLR5vY9zgBDI+wy/vnOKsr4yzm20rkTQP7ib65HlqzgT7KJg0FRjdbKHFQ/KEKAAyAIuxC3l41AKfIJfx/4+9kkwb5MFtPw8wAOdUaEO/sOXxS/UPiy+zifI/br9uvRxbLHtOy0Ou+gqeF4XG7u0cvs6gbo/RQwi1Sa5jmzsGZ3LInw3W45LTUtiiM2lTAoeSruFqwQFnCgztIyzObvehpaHd+ktXxUEVZr02/uIIHrbijO+2VH+iU7ZuonrLuz8PTP5LX70fkHODFGdl/urhYqZCeBbbgPMdrIbiB/68SL4mamGrarCAK6vRTm5KbsqjHe3LsGuMw0V8FieBGH9tneWjhJbwf4LN7CEb4IQwy6YPW2Ljlp21TDcMu6m/IV/k6FeBqWz934z1gjzaBXrePd//Sj52SY2hUhsi8rOCKWs4y36+atecZJJHmfvmI5Snv4xZalm8UnZgtZf6wlmpD2LED8ldMkFYTcqW7pv32CH/6fq/I5B6iY8Ey9QT9WMm8x2hyMbE00CuE1mdoRTIAVIGsiKOPNLfCid1G+e7J2c1JsTk2U4I8AUVyHQe/hqP/c4ObzDapePxZgkNvrqXebjU+VrfW1BD+KknVckHWmga8jmFqInfUsiBH6kFfTZ1vHnaIMUVjQT/UFS0F/3AJXpWjV8rGyTthA10I/PU5TmCCiyhTxdigirFyfEgIg4m/y0N7KFcrZGs7ZZX+9tVdgG9warif+
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: gaganeggday
    type: kubernetes.io/dockerconfigjson
status: {}
---
