apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: pipelines-service-role-binding
  namespace: ghegde-cicd-environment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-clusterrole
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: ghegde-cicd-environment
---
